baseURL = "https://adhadse.github.io/"
relativeURLs = true
languageCode = "en-us"
title = "Anurag Dhadse"
theme = "hana"
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 2